name: DeepTrainer

channels:
  - pytorch
  - conda-forge
  - defaults
  - nvidia

dependencies:
  - python=3.11
  - pytorch=2.5.1
  - torchvision
  - pytorch-cuda=12.4
  - lightning
  - torchmetrics

  - pip>=23
  - pip:
      - hydra-optuna-sweeper
      - hydra-colorlog
      - rootutils
      - torch-summary
      - timm
      - onnx
      - onnxruntime-gpu
      - torchinfo
      - hydra-core
      - rich
      - pre-commit
      - pytest
      - wandb
      - opencv-python
      - matplotlib
      - scikit-learn
      - ruff
      - segmentation-models-pytorch
      - ipywidgets
      - ipykernel
      - pandas
      - fastapi[standard]