# @package _global_

defaults:
  - _self_
  - data: mnist
  - model: mnist
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default
  - callbacks: rich_progress_bar
  - experiment: null

task_name: "eval"

predict: False

tags: ["dev"]
